# Generated by Django 5.2 on 2025-04-17 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoHogar',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(max_length=50)),
                ('codigo_invitacion', models.CharField(default='20A2CCC6FF', max_length=10, unique=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo del Hogar',
                'verbose_name_plural': 'Grupos del Hogar',
            },
        ),
        migrations.CreateModel(
            name='UsuarioGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateField(auto_now_add=True)),
                ('rol', models.CharField(default='Miembro', max_length=20)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grupohogar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario en Grupo',
                'verbose_name_plural': 'Usuarios en Grupos',
            },
        ),
    ]
