# Generated by Django 5.2 on 2025-04-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_grupohogar_codigo_invitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupohogar',
            name='codigo_invitacion',
            field=models.CharField(default='7AA5C420CC', max_length=10, unique=True),
        ),
    ]
