# Generated by Django 5.2 on 2025-06-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_grupohogar_codigo_invitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupohogar',
            name='codigo_invitacion',
            field=models.CharField(default='E74330B20C', max_length=10, unique=True),
        ),
    ]
