# Generated by Django 5.2 on 2025-05-05 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_alter_grupohogar_codigo_invitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id_tareas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tareas', models.CharField(max_length=50)),
                ('fecha_limite', models.DateField()),
                ('es_periodica', models.BooleanField(default=False)),
                ('frecuencia', models.CharField(blank=True, max_length=20, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('tiempo_estimado', models.IntegerField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.grupohogar')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
    ]
