# Generated by Django 5.2 on 2025-05-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_grupohogar_codigo_invitacion'),
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='npersonas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tareas',
            name='participantes',
            field=models.ManyToManyField(blank=True, null=True, related_name='tareas', to='core.usuariogrupo'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='frecuencia',
            field=models.IntegerField(default=1),
        ),
    ]
