# Generated by Django 5.2 on 2025-05-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_tareas_npersonas_tareas_participantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='frecuencia',
            field=models.IntegerField(default=1, verbose_name='Frecuencia (Veces a la semana)'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='npersonas',
            field=models.IntegerField(default=1, verbose_name='Número de personas necesarias'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='tiempo_estimado',
            field=models.FloatField(default=0.5),
        ),
    ]
