# Generated by Django 5.2 on 2025-05-29 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_alter_tareas_frecuencia_alter_tareas_npersonas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='npersonas',
        ),
    ]
