# Generated by Django 5.2 on 2025-05-30 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_grupohogar_codigo_invitacion'),
        ('tareas', '0004_remove_tareas_npersonas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='participantes',
        ),
        migrations.AddField(
            model_name='tareas',
            name='participantes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tareas', to='core.usuariogrupo'),
        ),
    ]
