# Generated by Django 5.2 on 2025-06-02 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_grupohogar_codigo_invitacion'),
        ('tareas', '0005_remove_tareas_participantes_tareas_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='participantes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='core.usuariogrupo'),
        ),
    ]
