# Generated by Django 5.2 on 2025-05-26 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0014_alter_grupohogar_codigo_invitacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCompra',
            fields=[
                ('id_lista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_lista', models.CharField(max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grupohogar')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoLista',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(default=1)),
                ('comprado', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('Fruta_Verdura', 'Fruta y Verdura')], max_length=50)),
                ('id_lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista_compra.listacompra')),
            ],
        ),
    ]
