# Generated by Django 5.2 on 2025-05-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productolista',
            name='unidades',
            field=models.CharField(blank=True, choices=[('ud', 'ud'), ('kg', 'kg'), ('bolsas', 'bolsas'), ('gr', 'gr')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productolista',
            name='tipo',
            field=models.CharField(choices=[('Fruta_Verdura', 'Fruta y Verdura'), ('Carne', 'Carne'), ('Pescado', 'Pescado'), ('Lacteos', 'Lacteos'), ('Congelados', 'Congelados'), ('Precocinados', 'Precocinados')], max_length=50),
        ),
    ]
