# Generated by Django 5.2 on 2025-05-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_compra', '0002_productolista_unidades_alter_productolista_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productolista',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Fruta_Verdura', 'Fruta y Verdura'), ('Carne', 'Carne'), ('Pescado', 'Pescado'), ('Lacteos', 'Lacteos'), ('Congelados', 'Congelados'), ('Precocinados', 'Precocinados'), ('Bebidas', 'Bebidas'), ('Otros', 'Otros'), ('Legumbres', 'Legumbres'), ('Conservas', 'Conservas'), ('Cereales o Pasta', 'Cereales o Pasta'), ('Harinas', 'Harinas'), ('Pan', 'Pan y Producto de panaderia'), ('Azucar', 'Azucar'), ('Cafe o Infusiones', 'Cafe o Infusiones'), ('Embutido', 'Embutido')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productolista',
            name='unidades',
            field=models.CharField(blank=True, choices=[('ud', 'ud'), ('kg', 'kg'), ('bolsas/bandeja', 'bolsas/bandeja'), ('gr', 'gr')], max_length=20, null=True),
        ),
    ]
