# Generated by Django 5.2 on 2025-05-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_compra', '0003_alter_productolista_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productolista',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Fruta/Verdura', 'Fruta y Verdura'), ('Carne', 'Carne'), ('Pescado', 'Pescado'), ('Lacteos', 'Lacteos'), ('Congelados', 'Congelados'), ('Precocinados', 'Precocinados'), ('Bebidas', 'Bebidas'), ('Otros', 'Otros'), ('Legumbres', 'Legumbres'), ('Conservas', 'Conservas'), ('Cereales o Pasta', 'Cereales o Pasta'), ('Harinas', 'Harinas'), ('Pan', 'Pan y Producto de panaderia'), ('Azucar', 'Azucar'), ('Cafe o Infusiones', 'Cafe o Infusiones'), ('Embutido', 'Embutido')], max_length=50, null=True),
        ),
    ]
