# Generated by Django 5.2 on 2025-04-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_grupohogar_codigo_invitacion'),
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='participantes',
            field=models.ManyToManyField(related_name='gastos', to='core.usuariogrupo'),
        ),
    ]
