# Generated by Django 5.2 on 2025-04-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_gasto_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='recurrente',
            field=models.BooleanField(default=False),
        ),
    ]
