# Generated by Django 5.2 on 2025-04-26 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_grupohogar_codigo_invitacion'),
        ('gastos', '0003_gasto_recurrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.grupohogar'),
        ),
    ]
