# Generated by Django 5.2 on 2025-06-02 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_grupohogar_codigo_invitacion'),
        ('gastos', '0005_alter_gasto_pagado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='pagado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuariogrupo'),
        ),
    ]
