# Generated by Django 5.2 on 2025-06-03 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_grupohogar_codigo_invitacion'),
        ('gastos', '0008_alter_gasto_pagado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='pagado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuariogrupo'),
        ),
    ]
